/PROG  FFPREP
/ATTR
OWNER		= MNEDITOR;
COMMENT		= "frame field probe prep";
PROG_SIZE	= 0;
CREATE		= DATE 26-01-01  TIME 00:00:00;
MODIFIED	= DATE 26-01-01  TIME 00:00:00;
FILE_NAME	= ;
VERSION		= 0;
LINE_COUNT	= 19;
MEMORY_SIZE	= 0;
PROTECT		= READ_WRITE;
TCD:  STACK_SIZE	= 0,
      TASK_PRIORITY	= 50,
      TIME_SLICE	= 0,
      BUSY_LAMP_OFF	= 0,
      ABORT_REQUEST	= 0,
      PAUSE_REQUEST	= 0;
DEFAULT_GROUP	= 1,*,*,*,*;
CONTROL_CODE	= 00000000 00000000;
/MN
   1:  UFRAME_NUM=0 ;
   2:  UTOOL_NUM=1 ;
   3:  PR[95]=LPOS    ;
   4:  PR[90]=LPOS    ;
   5:  PR[91]=LPOS    ;
   6:  PR[94]=LPOS    ;
   7:  PR[82]=LPOS    ;
   8:  PR[81]=LPOS    ;
   9:  PR[92]=LPOS    ;
  10:  PR[89]=LPOS    ;
  11:  PR[88]=LPOS    ;
  12:  PR[87]=LPOS    ;
  13:  PR[86]=LPOS    ;
  14:  PR[85]=LPOS    ;
  15:  PR[84]=LPOS    ;
  16:  PR[83]=LPOS    ;
  17:  PR[93]=LPOS    ;
  18:  PR[97]=LPOS    ;
  19:  PR[96]=LPOS    ;
/POS
/END
