# SPDX-FileCopyrightText: 2026 Enzo LEROY
# SPDX-License-Identifier: BUSL-1.1

"""Draw the CrossArm icon with the standard library only, and write it where it is used.

    python tools/make_icon.py

    packaging/crossarm.ico       icon of CrossArm.exe (PyInstaller --icon), 16 to 256 px
    src/crossarm/_icon.py        the same, as PNG data for the window title bar and taskbar

The mark: lines of a program on the left, an arrow on the right, on a dark rounded
square. Shapes are drawn with 4x4 supersampling for smooth edges at every size.
No brand colour of either robot maker is used: CrossArm is not affiliated with them.
"""

import base64
import struct
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BACKGROUND = (0x1F, 0x2A, 0x44)
WHITE = (0xFF, 0xFF, 0xFF)
ACCENT = (0x2E, 0xC4, 0xB6)
SIZES = (16, 24, 32, 48, 64, 128, 256)
SUPERSAMPLE = 4


def rounded_rect(x0, y0, x1, y1, r):
    def inside(x, y):
        cx, cy = min(max(x, x0 + r), x1 - r), min(max(y, y0 + r), y1 - r)
        return (x - cx) ** 2 + (y - cy) ** 2 <= r * r and x0 <= x <= x1 and y0 <= y <= y1

    return inside


def polygon(points):
    def inside(x, y):
        hit, n = False, len(points)
        for i in range(n):
            (xa, ya), (xb, yb) = points[i], points[(i + 1) % n]
            if (ya > y) != (yb > y) and x < (xb - xa) * (y - ya) / (yb - ya) + xa:
                hit = not hit
        return hit

    return inside


def bar(x0, x1, y, half):
    return rounded_rect(x0, y - half, x1, y + half, half)


# Painted in order: later layers cover earlier ones.
LAYERS = [
    (BACKGROUND, rounded_rect(0.03, 0.03, 0.97, 0.97, 0.22)),
    (WHITE, bar(0.17, 0.47, 0.33, 0.05)),
    (WHITE, bar(0.17, 0.38, 0.50, 0.05)),
    (WHITE, bar(0.17, 0.44, 0.67, 0.05)),
    (ACCENT, rounded_rect(0.50, 0.44, 0.68, 0.56, 0.02)),
    (ACCENT, polygon([(0.62, 0.28), (0.86, 0.50), (0.62, 0.72)])),
]


def render(size: int) -> bytes:
    """RGBA pixels, row by row."""
    out = bytearray()
    n = SUPERSAMPLE
    for py in range(size):
        for px in range(size):
            r = g = b = a = 0.0
            for sy in range(n):
                for sx in range(n):
                    x, y = (px + (sx + 0.5) / n) / size, (py + (sy + 0.5) / n) / size
                    colour = None
                    for fill, inside in LAYERS:
                        if inside(x, y):
                            colour = fill
                    if colour:
                        r, g, b, a = r + colour[0], g + colour[1], b + colour[2], a + 1
            count = n * n
            if a:
                out += bytes((round(r / a), round(g / a), round(b / a), round(255 * a / count)))
            else:
                out += b"\x00\x00\x00\x00"
    return bytes(out)


def png(size: int, rgba: bytes) -> bytes:
    def chunk(tag: bytes, data: bytes) -> bytes:
        return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)

    stride = size * 4
    raw = b"".join(b"\x00" + rgba[y * stride : (y + 1) * stride] for y in range(size))
    header = struct.pack(">IIBBBBB", size, size, 8, 6, 0, 0, 0)  # 8-bit RGBA
    return b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", header) + chunk(b"IDAT", zlib.compress(raw, 9)) + chunk(b"IEND", b"")


def ico(images: dict[int, bytes]) -> bytes:
    """Windows .ico holding PNG images (supported since Windows Vista)."""
    header = struct.pack("<HHH", 0, 1, len(images))
    entries, blobs, offset = b"", b"", 6 + 16 * len(images)
    for size, data in images.items():
        dim = 0 if size >= 256 else size  # 0 means 256
        entries += struct.pack("<BBBBHHII", dim, dim, 0, 0, 1, 32, len(data), offset)
        blobs += data
        offset += len(data)
    return header + entries + blobs


def main() -> None:
    images = {size: png(size, render(size)) for size in SIZES}
    (ROOT / "packaging" / "crossarm.ico").write_bytes(ico(images))
    module = ROOT / "src" / "CrossArm" / "_icon.py"
    encoded = {size: base64.b64encode(images[size]).decode("ascii") for size in (16, 32, 64)}
    lines = [
        "# SPDX-FileCopyrightText: 2026 Enzo LEROY",
        "# SPDX-License-Identifier: BUSL-1.1",
        "",
        '"""CrossArm icon as PNG data for Tk (title bar, taskbar). Generated by tools/make_icon.py: do not edit."""',
        "",
        "PNG = {",
        *(f'    {size}: "{data}",' for size, data in encoded.items()),
        "}",
        "",
    ]
    module.write_text("\n".join(lines), encoding="ascii")
    print(f"wrote packaging/crossarm.ico ({len(SIZES)} sizes) and src/crossarm/_icon.py")


if __name__ == "__main__":
    main()
